before_script:
  - export CXX=g++-4.8.3 CC=gcc-4.8.3
  # paths to local or network installation (the riscv toolchain and 
  # verilator are not built in a ci job in this case)
  - export QUESTASIM_HOME=/scratch/$USER/questasim
  - export QUESTASIM_VERSION=
  - export RISCV=/scratch/$USER/riscv_install
  - export VERILATOR_ROOT=/scratch/$USER/verilator-3.924
  # setup dependent paths
  - export PATH=${RISCV}/bin:$VERILATOR_ROOT/bin:${PATH}
  - export LIBRARY_PATH=$CI_PROJECT_DIR/tmp/lib
  - export LD_LIBRARY_PATH=$CI_PROJECT_DIR/tmp/lib
  - export C_INCLUDE_PATH=$CI_PROJECT_DIR/tmp/include:$VERILATOR_ROOT/include
  - export CPLUS_INCLUDE_PATH=$CI_PROJECT_DIR/tmp/include:$VERILATOR_ROOT/include
  # number of parallel jobs to use for make commands and simulation
  - export NUM_JOBS=4
  - ci/make-tmp.sh
  - git submodule update --init --recursive
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  script:
    - ci/install-fesvr.sh
    - ci/build-riscv-tests.sh
    - make clean
    - make build questa_version=$QUESTASIM_VERSION
    - make verilate verilator=$VERILATOR_ROOT/bin/verilator
  artifacts:
      paths:
        - tmp 

# rv64ui-p-* and rv64ui-v-* tests    
run-asm-tests-questa:
  stage: test
  script:
    - make -j${NUM_JOBS} run-asm-tests questa_version=$QUESTASIM_VERSION
  dependencies:
    - build

run-benchmarks-questa:
  stage: test
  script:
    - make -j${NUM_JOBS} run-benchmarks questa_version=$QUESTASIM_VERSION
  dependencies:
    - build    

# rv64ui-p-* tests
run-asm-tests1-verilator:
  stage: test
  script:
    - make -j${NUM_JOBS} run-asm-tests1-verilator verilator=$VERILATOR_ROOT/bin/verilator
  dependencies:
    - build

# rv64ui-v-* tests
run-asm-tests2-verilator:
  stage: test
  script:
    - make -j${NUM_JOBS} run-asm-tests2-verilator verilator=$VERILATOR_ROOT/bin/verilator
  dependencies:
    - build    

run-benchmarks-verilator:
  stage: test
  script:
    - make -j${NUM_JOBS} run-benchmarks-verilator verilator=$VERILATOR_ROOT/bin/verilator
  dependencies:
    - build


