language: cpp
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $RISCV
    $VERILATOR_ROOT

# required packages to install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - python-pexpect
      - libusb-1.0-0-dev
      - device-tree-compiler
env:
  global:
    - RISCV="/home/travis/riscv_install"
    - VERILATOR_ROOT="/home/travis/verilator-3.924/"

branches:
  only:
  - master
  - ariane_next

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8
  # setup dependent paths
  - export PATH=$RISCV/bin:$VERILATOR_ROOT/bin:$PATH
  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/tmp/lib
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/tmp/lib
  - export C_INCLUDE_PATH=$TRAVIS_BUILD_DIR/tmp/include:$VERILATOR_ROOT/include
  - export CPLUS_INCLUDE_PATH=$TRAVIS_BUILD_DIR/tmp/include:$VERILATOR_ROOT/include
  # number of parallel jobs to use for make commands and simulation
  - export NUM_JOBS=4
  - ci/make-tmp.sh
  - git submodule update --init --recursive

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      name: prepare cache
      script:
        - ci/build-riscv-gcc.sh
        - ci/install-verilator.sh
    - stage: test
      name: run riscv benchmarks
      script:
        - ci/install-fesvr.sh
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-benchmarks-verilator verilator=$VERILATOR_ROOT/bin/verilator
    # rv64ui-p-* tests
    - stage: test
      name: run rv64ui-p-* asm tests
      script:
        - ci/install-fesvr.sh
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-asm-tests1-verilator verilator=$VERILATOR_ROOT/bin/verilator
    # rv64ui-v-* tests
    - stage: test
      name: run rv64ui-v-* asm tests
      script:
        - ci/install-fesvr.sh
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-asm-tests2-verilator verilator=$VERILATOR_ROOT/bin/verilator
    
# extra time during long builds
install: travis_wait
